### ISSUE TITLE
Example #5

### ISSUE THREAD

**Issue by jerbearbearbear** [jerbearbearbear/class-coding-2-pointers-template#2]
Example 5# needs to be worked on before I send the pull request tonight so that everyone in the group has contributed.

**Comment by markify** [comment]
commited attempt 5 example 5

**Comment by OleksandrNibyt** [comment]
example 5 does not seem to be working

**Comment by jerbearbearbear** [comment]
I believe example 8 and 9 are not working as well. But as long as we "attempted" all the to-dos and submit a pull request and have it built on Travis we will all get credit no matter if it passes or fails.

We worked on the last 3 to-dos after lab today so there should be no problems with not attempting everything.

**Comment by OleksandrNibyt** [comment]
i am trying to get example 8 to work

**Comment by OleksandrNibyt** [comment]
for example 5 i did that -> int i = *prt; so it seems to cancel error message for that part.

**Comment by jerbearbearbear** [comment]
If you get any of them to work, commit push and let me know I'll update the pull request when I get home in 30 mins

**Comment by OleksandrNibyt** [comment]
ok

**Comment by OleksandrNibyt** [comment]
namespace example8 {
void example() {

  //array of pointers
  int var[MAX] = {10, 100, 200};
  //TODO 8 define an integer pointer of size MAX
  size_t ptr = (sizeof(MAX));
  for (int i = 0; i < MAX; i++) {
    //TODO 8// assign the address of integer.
    ptr = (size_t) (size_t) (int*) 0x100100080;
  }
  for (int i = 0; i < MAX; i++) {
    //TODO 8
    cout << "Value of var[" << i << "] = ";
    //ptr = &var;
  }
  cout << ptr; // just to see what it will print out 
this what so far i have , i am not sure if it is correct, but it doesn't cause errors

**Comment by jerbearbearbear** [comment]
Interesting. I'm not exactly sure what's going on in this part:
//TODO 8// assign the address of integer.
ptr = (size_t) (size_t) (int*) 0x100100080;
But if there is no errors then update it so I can try to run it and see what it does.

**Comment by OleksandrNibyt** [comment]
//array of pointers
int var[MAX] = {10, 100, 200};  // this is just array, not an array of pointers( trying to find a way to do it
i will push in a couple minutes. I just did some stuff so that errors won't show up

**Comment by OleksandrNibyt** [comment]
i have pushed it

**Comment by OleksandrNibyt** [comment]
could you do that travis thing that has to be done ?

**Comment by OleksandrNibyt** [comment]
using namespace std;
const int MAX = 3;

int main ()
{
   int  var[MAX] = {10, 100, 200};
   int *ptr[MAX];

   for (int i = 0; i < MAX; i++)
   {
      ptr[i] = &var[i]; // assign the address of integer.
   }
   for (int i = 0; i < MAX; i++)
   {
      cout << "Value of var[" << i << "] = ";
      cout << *ptr[i] << endl;
   }
   return 0;
}
so thats what i found, seems very similar to example 8

**Comment by jerbearbearbear** [comment]
the other guy named JiawenZhu just pushed a commit and now the error is back

**Comment by OleksandrNibyt** [comment]
lol

**Comment by OleksandrNibyt** [comment]
the code i found is exactly what we need for example 8, so could you past that in, and example 9 is same as example 8, but char instead of int

**Comment by OleksandrNibyt** [comment]
so what do we do? i do a pull and fix part 8 and 9 or what?

**Comment by jerbearbearbear** [comment]
one sec, im fixing 5 first

**Comment by OleksandrNibyt** [comment]
ok

**Comment by jerbearbearbear** [comment]
ok, so put in what you got for 8 and 9 now

**Comment by jerbearbearbear** [comment]
you can pull now

**Comment by OleksandrNibyt** [comment]
ok

**Comment by OleksandrNibyt** [comment]
well, it works, not so sure about example 9 though, but i guess its ok. I will push now.

**Comment by OleksandrNibyt** [comment]
i guess we good for tonight, only run it through travis thing or something like that, and submit to Omar

**Comment by jerbearbearbear** [comment]
that example you found for number 8 is like the exact same problem lol
i also found an exact copy of number 10 too so im sure it works.
but number 5 goes on an infinite loop when i run it

**Comment by jerbearbearbear** [comment]
i will pull now, we should be ok

**Comment by OleksandrNibyt** [comment]
ok)

**Comment by jerbearbearbear** [comment]
![screenshot from 2016-09-22 23-10-06](https://cloud.githubusercontent.com/assets/21187618/18775856/beb30ed4-8119-11e6-8a7d-4ac47855cdad.png)

**Comment by jerbearbearbear** [comment]
lol

**Comment by OleksandrNibyt** [comment]
whats that?

**Comment by JiawenZhu** [comment]
I fixed some of bugs. Ex5 is still buggy. I comment it out. If you guys want to pull. You can create a new github repositories on your pc / mac using git clone in different forder. I'm sorry for the inconvience.

**Comment by JiawenZhu** [comment]
Code is working now. You can run it.

**Comment by OleksandrNibyt** [comment]
hi guys) 
have you managed to connect travis with git hub for home work 2.5?

**Comment by jerbearbearbear** [comment]
I was able to get it. I didn't see it at first because I thought the hw would be under my repositories but it's under the csc340 class repositories. Try to find the affiliated repositories button and you should see our class repo click on it and your build should show of its passing there.

Get Outlook for iOShttps://aka.ms/o0ukef

On Sun, Sep 25, 2016 at 8:16 PM -0700, "OleksandrNibyt" <notifications@github.com<mailto:notifications@github.com>> wrote:

hi guys)
have you managed to connect travis with git hub for home work 2.5?

##

**Comment by jerbearbearbear** [comment]
i forgot to add. you need to use travis-ci.COM not org as com is the where you can see you private repos and the one we are pushing is private on github

**Comment by OleksandrNibyt** [comment]
i have already done hw in cLion, but howdy we run it through travis and git hub?

**Comment by jerbearbearbear** [comment]
just commit and push. it should show up on github and travis

**Comment by OleksandrNibyt** [comment]
thank you)

**Comment by OleksandrNibyt** [comment]
I am having trouble connecting travisci with github(

**Comment by jerbearbearbear** [comment]
if you have commited and pushed then the homework should show up on travis-ci.com (not org)
